### ISSUE TITLE
Device unique id parameter

### ISSUE THREAD

**Issue by leikoilja** [leikoilja/glocaltokens#75]
Let's find a way to extract a unique ID from homegraph or `eureka` endpoint to pass it for each of devices

**Comment by ArnyminerZ** [comment]
I was taking a look at [GHLAPI](https://rithvikvibhu.github.io/GHLocalApi/#operation/EurekaInfo) to see which element would fit our needs. And I think the best options are:
* `cloud_device_id`: which may not be the best option, since it seems a pretty private ID, so a copy-paste from the log may show up this info.
* `public_key`: may be a good option, states that it's public, so there won't be any privacy issues, and I believe it should be unique, but it might be a bit too large.
* `ssdp_udn`: Not sure what this is
* `uma_client_id`: Not sure what this is

What do you think would be the best option?

**Comment by KapJI** [comment]
`cloud_device_id` sounds good.

**Comment by leikoilja** [comment]
Good investigation, @ArnyminerZ 🙌 
`AppDeviceID` does not seem to be unique thou.
Seems like both `cloud_device_id` and `mac_address` are present in `eureka` endpoint, so both seems to be legitimate options. I am in favour of `mac_address` thou.
